apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: mypod
    spec:
      containers:
        - name: mycontainer
          image: vecps-jichu-product.cargo.io/infcs/platform_web_job:a35dde38a2fab56225197946ef281bdb
          # image: hub.byted.org/infcs/platform_web_job:a35dde38a2fab56225197946ef281bdb
          # command: ["sh", "-c", 'cd platform-job/platform-job && yarn upload']
          env:
            - name: selfenv
              value: "hello"

      restartPolicy: OnFailure